"""Embedded configuration templates."""

from plsec.configs.templates import (
    CLAUDE_MD_BALANCED,
    CLAUDE_MD_STRICT,
    OPENCODE_JSON_BALANCED,
    OPENCODE_JSON_STRICT,
    PLSEC_YAML_TEMPLATE,
    PRE_COMMIT_HOOK,
    TRIVY_SECRET_YAML,
)

__all__ = [
    "CLAUDE_MD_STRICT",
    "CLAUDE_MD_BALANCED",
    "OPENCODE_JSON_STRICT",
    "OPENCODE_JSON_BALANCED",
    "PLSEC_YAML_TEMPLATE",
    "TRIVY_SECRET_YAML",
    "PRE_COMMIT_HOOK",
]
