"""Artifact inventory model -- discovers and catalogues plsec's filesystem footprint.

Provides dataclasses and discovery functions used by ``plsec install``,
``plsec reset``, and ``plsec uninstall`` to understand what plsec has
created on the user's system.

All discovery functions accept explicit path arguments rather than
calling ``get_plsec_home()`` internally, making them testable with
``tmp_path`` and no mocking.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from plsec.core.agents import AGENTS, AgentSpec

# Project-local filenames that plsec creates.
# Each tuple is (filename, description, created_by).
_PROJECT_FILES: list[tuple[str, str, str]] = [
    ("plsec.yaml", "Project security configuration", "init, secure"),
    (".plsec-manifest.json", "File integrity manifest", "integrity"),
    (".pre-commit-config.yaml", "Git pre-commit hook config", "secure"),
]

# Header markers used to identify plsec-generated content.
# If a project-local agent config contains this marker it is considered
# to match the plsec template (safe to remove without warning).
PLSEC_MARKER = "plsec"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class Artifact:
    """A file or directory created by plsec."""

    # Absolute path to the artifact
    path: Path
    # Classification for grouping in output
    category: Literal[
        "global_config",
        "global_log",
        "global_runtime",
        "global_directory",
        "external_config",
        "project_config",
        "project_manifest",
    ]
    # Human-readable description
    description: str
    # Size in bytes (0 for directories, computed at discovery time)
    size_bytes: int = 0
    # Whether the file can be safely removed
    removable: bool = True
    # Whether the file matches a plsec template (for project files)
    matches_template: bool = True


@dataclass
class Inventory:
    """Complete inventory of plsec artifacts on the system."""

    artifacts: list[Artifact] = field(default_factory=list)

    @property
    def global_artifacts(self) -> list[Artifact]:
        """Artifacts under ~/.peerlabs/plsec/ and external agent configs."""
        return [
            a
            for a in self.artifacts
            if a.category.startswith("global_") or a.category == "external_config"
        ]

    @property
    def project_artifacts(self) -> list[Artifact]:
        """Artifacts in the project directory."""
        return [a for a in self.artifacts if a.category.startswith("project_")]

    @property
    def total_size(self) -> int:
        """Total size of all artifacts in bytes."""
        return sum(a.size_bytes for a in self.artifacts)

    @property
    def global_size(self) -> int:
        """Total size of global artifacts in bytes."""
        return sum(a.size_bytes for a in self.global_artifacts)

    @property
    def project_size(self) -> int:
        """Total size of project artifacts in bytes."""
        return sum(a.size_bytes for a in self.project_artifacts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def format_size(size_bytes: int) -> str:
    """Format a byte count as a human-readable string.

    Examples: ``0 B``, ``1.2 KB``, ``3.4 MB``.
    """
    if size_bytes < 1024:
        return f"{size_bytes} B"
    if size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    return f"{size_bytes / (1024 * 1024):.1f} MB"


def _file_size(path: Path) -> int:
    """Return file size in bytes, 0 for directories or missing files."""
    if path.is_file():
        return path.stat().st_size
    return 0


def _matches_plsec_template(path: Path) -> bool:
    """Check if a file appears to be generated by plsec.

    Looks for the ``PLSEC_MARKER`` string anywhere in the first 2 KB
    of the file content.  Binary files or read errors return False.
    """
    try:
        content = path.read_text(errors="ignore")[:2048]
        return PLSEC_MARKER in content.lower()
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Discovery functions
# ---------------------------------------------------------------------------


def discover_global_artifacts(plsec_home: Path) -> list[Artifact]:
    """Discover all plsec artifacts under the global home directory.

    Walks ``~/.peerlabs/plsec/`` and classifies each file and directory.
    Returns an empty list if the directory does not exist.
    """
    if not plsec_home.is_dir():
        return []

    artifacts: list[Artifact] = []

    # Classify files by their parent directory
    for item in sorted(plsec_home.rglob("*")):
        rel = item.relative_to(plsec_home)
        rel_str = str(rel)

        if item.is_dir():
            artifacts.append(
                Artifact(
                    path=item,
                    category="global_directory",
                    description=f"{rel_str}/",
                    size_bytes=0,
                )
            )
            continue

        # Classify files by location and name.
        # Order matters: check directory-based categories first, then
        # fall back to extension-based heuristics.
        category: Literal[
            "global_config",
            "global_log",
            "global_runtime",
            "global_directory",
            "external_config",
            "project_config",
            "project_manifest",
        ]
        if rel_str.startswith("logs/"):
            category = "global_log"
        elif rel_str.endswith(".pid") or rel_str == ".installed.json":
            category = "global_runtime"
        else:
            category = "global_config"

        artifacts.append(
            Artifact(
                path=item,
                category=category,
                description=rel_str,
                size_bytes=_file_size(item),
            )
        )

    return artifacts


def discover_external_artifacts(
    agents: dict[str, AgentSpec] | None = None,
) -> list[Artifact]:
    """Discover agent configs deployed to native locations outside plsec home.

    For example, ``~/.config/opencode/opencode.json``.
    """
    if agents is None:
        agents = AGENTS

    artifacts: list[Artifact] = []
    for spec in agents.values():
        if spec.global_config_dir is None:
            continue
        config_path = spec.global_config_dir / spec.config_filename
        if config_path.is_file():
            artifacts.append(
                Artifact(
                    path=config_path,
                    category="external_config",
                    description=f"{spec.display_name} config ({config_path})",
                    size_bytes=_file_size(config_path),
                    matches_template=_matches_plsec_template(config_path),
                )
            )

    return artifacts


def discover_project_artifacts(
    project_dir: Path,
    agents: dict[str, AgentSpec] | None = None,
) -> list[Artifact]:
    """Discover plsec files in a project directory.

    Checks for agent config files, plsec.yaml, manifests, and other
    files that plsec commands create.
    """
    if agents is None:
        agents = AGENTS

    artifacts: list[Artifact] = []

    # Agent config files (CLAUDE.md, opencode.json)
    for spec in agents.values():
        config_path = project_dir / spec.config_filename
        if config_path.is_file():
            artifacts.append(
                Artifact(
                    path=config_path,
                    category="project_config",
                    description=f"{spec.display_name} config",
                    size_bytes=_file_size(config_path),
                    matches_template=_matches_plsec_template(config_path),
                )
            )

    # Known project files
    for filename, description, _created_by in _PROJECT_FILES:
        file_path = project_dir / filename
        if file_path.is_file():
            category: Literal[
                "global_config",
                "global_log",
                "global_runtime",
                "global_directory",
                "external_config",
                "project_config",
                "project_manifest",
            ]
            if filename == ".plsec-manifest.json":
                category = "project_manifest"
            else:
                category = "project_config"
            artifacts.append(
                Artifact(
                    path=file_path,
                    category=category,
                    description=description,
                    size_bytes=_file_size(file_path),
                )
            )

    return artifacts


def discover_all(
    plsec_home: Path,
    project_dir: Path,
    agents: dict[str, AgentSpec] | None = None,
) -> Inventory:
    """Build complete inventory of all plsec artifacts."""
    if agents is None:
        agents = AGENTS

    artifacts: list[Artifact] = []
    artifacts.extend(discover_global_artifacts(plsec_home))
    artifacts.extend(discover_external_artifacts(agents))
    artifacts.extend(discover_project_artifacts(project_dir, agents))

    return Inventory(artifacts=artifacts)
